# 역행렬(inverse matrix)

정방 행렬 $A$에 대한 역행렬(inverse matrix) $A^{−1}$ 은 원래의 행렬 $A$와 다음 관계를 만족하는 정방 행렬을 말한다. 
$I$는 항등 행렬(identity matrix)이다.

$$A^{−1}A=AA^{−1}=I$$

역행렬이 존재하는 행렬을 가역행렬(invertible matrix), 반대로 역행렬이 존재하지 않는 행렬을 특이행렬(singular matrix)이라고 한다.

## 역행렬의 성질
역행렬은 다음 성질을 만족한다. 

전치 행렬의 역행렬은 역행렬의 전치 행렬과 같다. 따라서 대칭 행렬의 역행렬도 대칭 행렬이다.

$$(A^T)^−1=(A^{−1})^T$$

두 개 이상의 정방 행렬의 곱은 같은 크기의 정방 행렬이 되는데 이러한 행렬의 곱의 역행렬은 다음 성질이 성립한다.

$$(AB)^{−1}=B^{−1}A^{−1}$$

$$(ABC)^{−1}=C^{−1}B^{−1}A^{−1}$$

## 역행렬과 선형 연립방정식의 해

선형 연립방정식에서 미지수의 수와 방정식의 수가 같다면 계수행렬 $A$는 정방행렬이 된다. 만약 행렬 $A$의 역행렬 $A^{−1}$이 존재한다면 역행렬의 정의로부터 선형 연립방정식의 해는 다음처럼 구할 수 있다.

$$Ax=b$$

$$x=A^{−1}b$$

In [1]:
# numpy로 역행렬 구하기

A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1]])

# array([[1, 1, 0],
#        [0, 1, 1],
#        [1, 1, 1]])

Ainv = np.linalg.inv(A)
Ainv

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

In [2]:
# 역행렬과 선형 연립방정식의 해 구하기

b = np.array([[2], [2], [3]])
x = Ainv @ b

A @ x - b # 일치하는지 확인


array([[0.],
       [0.],
       [0.]])

In [4]:
# 연습 문제 2.4.5

# from sklearn.datasets import load_boston
# boston = load_boston()
# X = boston.data
# y = boston.target
# A = X[:4, [0, 4, 5, 6]]  # 'CRIM', 'NOX', 'RM', 'AGE'
# b = y[:4]

# Ainv = np.linalg.inv(A)
# x = Ainv @ b

# *데이터 지워짐!*

In [2]:
# 최소자승문제: 벡터의 놈(norm)을 최소화

# 풀이 과정
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1], [1, 1, 2]])
b = np.array([[2], [2], [3], [4.1]])

Apinv = np.linalg.inv(A.T @ A) @ A.T
# Apinv == array([[ 0.33333333, -1.        ,  0.33333333,  0.33333333],
#                [ 0.5       ,  1.        ,  0.        , -0.5       ],
#                [-0.5       ,  0.        ,  0.        ,  0.5       ]])

x = Apinv @ b
# x == array([[1.03333333],
#            [0.95      ],
#            [1.05      ]])

print(A @ x) # b값과 유사

[[1.98333333]
 [2.        ]
 [3.03333333]
 [4.08333333]]


In [3]:
# lstsq() 명령으로 동일한 계산 가능

x, resid, rank, s = np.linalg.lstsq(A, b)
x 

# resid는 놈의 제곱이며 (array([0.00166667]), 0.001666666666666655)

array([[1.03333333],
       [0.95      ],
       [1.05      ]])